defaults:
  - basis
  - managers: auto_atom/basis
  - demonstrators: auto_atom/basis
  - samplers: ros_struct
  - _self_
  - override hydra/job_logging: custom

visualizer: null

managers:
  auto_atom:
    env:
      viewer: null
