# @package _global_

defaults:
  - auto_atom/aao_configs/arrange_flowers_gs@managers.auto_atom
  - auto_atom/aao_configs/arrange_flowers_gs@demonstrator.component
  - auto_atom/basis
  - auto_atom/gs_mixin
  - _self_


demonstrator:
  component:
    update_freq: 15
