# @package _global_

defaults:
  - /managers/auto_atom/class: rule_based
  - /managers/auto_atom/task: pick_and_place
  - /managers/auto_atom/aao_configs@managers.auto_atom: ${managers/auto_atom/task}
  - /managers/auto_atom/aao_configs/common_vars
  - _self_

assets_dir: third_party/auto-atomic-operation/assets
managers:
  self_manager:
    _target_: airdc.managers.basis.SelfManager
    on_reach: abandon
  auto_atom:
    env:
      batch_size: ${batch_size}
      structured: false

bg3dgs_dir: ${managers.auto_atom.bg3dgs_dir}
bg3dgs_name: ${managers.auto_atom.bg3dgs_name}

model_name: ${managers.auto_atom.model_name}
scene_name: ${managers.auto_atom.scene_name}
task_name: ${managers.auto_atom.task_name}
operations: ${managers.auto_atom.env.operations}
objects: ${managers.auto_atom.env.mask_objects}

sampler:
  encoder:
    cfg:
      frame_format: rgb24
