# @package _global_

defaults:
  - auto_atom/aao_configs/open_hinge_door@managers.auto_atom
  - auto_atom/aao_configs/open_hinge_door@demonstrator.component
  - auto_atom/basis
  - _self_

task_name: open_hinge_door
scene_name: open_close_hinge_door

demonstrator:
  component:
    sim_freq: 600
    update_freq: 10

sampler:
  task_info:
    task_description: open the hinge door
    skill: [pull]
    object: [hinge_door]
