# @package _global_

defaults:
  - basis

demonstrator:
  components:
    groups:
      - /
      # - /
    names:
      - follow # unified name
      # - follow_camera
    instances:
      - _target_: airbot_ie.robots.airbot_play.AIRBOTPlay
        port: 50050
        components:
          - arm
          - eef
      # - _target_: airdc.common.devices.cameras.v4l2.V4L2Camera
    roles:
      - l
      # - o

dataset:
  directory: airbot_play
