# @package _global_

task_name: pick_place

demonstrator:
  _target_: airdc.common.demonstrators.single.SingleComponentDemonstrator
  component:
    _target_: airdc.common.systems.mujoco_env.MujocoEnv
    name: mujoco_env
    model_path: third_party/auto-atomic-operation/assets/xmls/scenes/${task_name}/demo.xml
    sim_freq: 500
    update_freq: 100
    enabled_sensors:
      - camera
      - pose
      - tactile
      - joint_position
      - joint_velocity
      - joint_effort
    mask_objects: ["source_block", "target_pedestal"]
    operations: ["pick", "place", "push", "pull", "press"]
    interests:
      - ["source_block", "target_pedestal"]
      - ["pick", "place"]
    cameras:
      - name: hand_cam
        width: 1280
        height: 720
        enable_color: true
        enable_depth: true
        enable_mask: false
        enable_heat_map: true
        parent_frame: eef_pose
      - name: front_cam
        width: 1280
        height: 720
        enable_color: true
        enable_depth: true
        enable_mask: false
        enable_heat_map: true
      - name: side_cam
        width: 1280
        height: 720
        enable_color: true
        enable_depth: true
        enable_mask: false
        enable_heat_map: true
    operators:
      - name: arm
        arm_actuators: []
        eef_actuators: [fingers_actuator]
        eef_output_name: eef
        pose_site: eef_pose
        imu_acc: imu_acc
        imu_gyro: imu_gyro
        imu_quat: imu_quat
        pose_sensor_pos: global_gripper_pos
        pose_sensor_quat: global_gripper_quat
        tactile_prefixes: ["left_", "right_"]
    viewer:
      lookat: [0.04, 0.0, 0.1]
      distance: 0.55
      azimuth: 135
      elevation: -28
      step_delay: 0.03
      hold_seconds: 3.0
log_jitter: false
visualizer:
  swap_rgb_bgr: true
managers:
  self_manager:
    _target_: airdc.managers.basis.SelfManager
    on_reach: abandon
  auto_atom:
    _target_: airdc.managers.auto_atom.AutoAtomManager
    backend: auto_atom.backend.mjc.mujoco_backend.build_mujoco_backend
    operators:
      - name: arm

sampler:
  av_coder:
    frame_format: rgb24
  task_info:
    operator: auto_atom
    station: mujoco

sample_limit:
  end_round: 1000
  # rounds: 1000

# update as fast as possible for simulation since the actual update rate is determined by the simulation frequency
update_rate: 200
