# @package _global_

demonstrator:
  _target_: airdc.common.demonstrators.single.SingleComponentDemonstrator
  component:
    _target_: airdc.common.systems.mujoco_env.MujocoEnv
    model_path: third_party/xml/scene_single_arm.xml
    arm_mode: single
    enabled_sensors:
      - camera
      - pose
      - joint_position
      - joint_velocity
      - joint_effort
      - tactile
    mask_objects: ["floor_1_room_main", "left_follower"]
    operations: ["grasp", "push", "place", "pull", "rotate"]
    cameras:
      - name: hand_cam
        width:  1280
        height: 720
        enable_color: true
        enable_depth: true
        enable_mask: false
        enable_heat_map: true
log_jitter: false
