# @package _global_

sampler:
  task_info:
    operator: Anonymous
    station: ptk-001
    task_name: pick_and_place_blocks
    task_description: Pick up the building blocks scattered on the table one by one and put them into the bowl next to them.
    task_id: "135"
    skill:
      - pick
      - place
    object:
      - wooden_blocks
      - bowl
    scene: desktop
    subtasks:
      - skill: pick
        description: pick the wooden blocks from the table with the gripper
        description_zh: 用夹爪从碗中拾取木制积木
      - skill: place
        description: place the wooden blocks into the bowl with the gripper
        description_zh: 用夹爪将木制积木放入碗中
