# @package _global_

cam_width: 1280
cam_height: 720
enable_color: true
enable_depth: true
enable_mask: false
enable_heat_map: true
env_name: auto_atom_env

batch_size: 2

demonstrator:
  _target_: airdc.common.demonstrators.single.SingleBatchedComponentDemonstrator
  # _target_: airdc.common.demonstrators.single.SingleComponentDemonstrator
  component:
    batch_size: ${batch_size}
    name: ${env_name}
    viewer:
      lookat: [0.04, 0.0, 0.1]
      distance: 0.55
      azimuth: 135
      elevation: -28
      step_delay: 0.03
      hold_seconds: 3.0
    # structured: true

log_jitter: false
visualizer:
  swap_rgb_bgr: true

sampler:
  av_coder:
    frame_format: rgb24
  task_info:
    operator: auto_atom
    station: mujoco

sample_limit:
  size: 200
  # end_round: 300
  rounds: 1

# update as fast as possible for simulation since the actual update rate is determined by the simulation frequency
update_rate: 1000
