# @package _global_

batch_size: 2

demonstrator:
  _target_: airdc.common.demonstrators.single.SingleBatchedComponentDemonstrator
  # _target_: airdc.common.demonstrators.single.SingleComponentDemonstrator
  component:
    _target_: airdc.common.systems.mujoco_env.BatchedMujocoEnv
    name: ${task_name}

log_jitter: false
visualizer:
  swap_rgb_bgr: true

sample_limit:
  size: 300
  # end_round: 300
  rounds: 1

# update as fast as possible for simulation since the actual update rate is determined by the simulation frequency
update_rate: 1000
