# @package _global_

defaults:
  - mixin
  - _self_

robot_gs_dir: ${managers.auto_atom.robot_gs_dir}
eef_gs_dir: ${managers.auto_atom.eef_gs_dir}
model_name: demo_gs_airbot_play
door_name: door0
bg3dgs_name: bg0
door_side: ${managers.auto_atom.door_side}
